[package]
name = "astronomy_engine"
version = "0.1.0"
edition = "2024_07"

[dependencies]
astronomy_engine_v6 = { path = "../research/astronomy_engine_v6" }
starknet = "2.16.1"

[[target.starknet-contract]]
