[workspace]
members = [
  "crates/astronomy_engine_v5",
  "crates/astronomy_engine_api",
  "crates/astronomy_engine_eval_runner",
]

[workspace.package]
version = "0.1.0"
edition = "2024_07"

[workspace.dependencies]
