[package]
name = "astronomy_engine"
version.workspace = true
edition.workspace = true

[dependencies]
engine_v6 = { path = "../engine_v6" }
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[scripts]
test.workspace = true

[[target.starknet-contract]]
